### ISSUE TITLE
Error for api when create a project from kettle on Windows

### ISSUE THREAD

**Issue by johnnestebann** [popphp/pop-kettle#3]
Fatal error: Uncaught Error: Call to undefined method Pop\Http\Response::setHeaders() in C:\Users\user\popphp-framework\app\src\Http\Api\Controller\AbstractController.php:25
Stack trace:
#0 C:\Users\user\popphp-framework\app\src\Http\Api\Controller\IndexController.php(15): App\Http\Api\Controller\AbstractController->send(200, Array)
#1 C:\Users\user\popphp-framework\vendor\popphp\popphp\src\Controller\AbstractController.php(71): App\Http\Api\Controller\IndexController->index()
#2 C:\Users\user\popphp-framework\vendor\popphp\popphp\src\Application.php(510): Pop\Controller\AbstractController->dispatch('index', NULL)
#3 C:\Users\user\popphp-framework\vendor\popphp\popcorn\src\Pop.php(410): Pop\Application->run(true, NULL)
#4 C:\Users\user\popphp-framework\public\index.php(9): Popcorn\Pop->run()
#5 {main} thrown in C:\Users\user\popphp-framework\app\src\Http\Api\Controller\AbstractController.php on line 25

**Comment by nicksagona** [comment]
This looks like it's prob a BC break with the new updated/refactored `pop-http` component. `setHeaders()` was deprecated in favor of `addHeaders`() I'll look into it.

**Comment by nicksagona** [comment]
Ok this has been fixed. It was BC breaks with the newly refactored components that are complete but will be released with the 4.5.0 version of the framework.
