### ISSUE TITLE
Feature request: Creating controllers, views etc with kettle

### ISSUE THREAD

**Issue by ghost** [popphp/pop-kettle#5]
Creating controllers, views etc by running some kettle commands would be nice for saving some time etc. What do you think about it?

**Comment by nicksagona** [comment]
The kettle script already provides this via the `./kettle app:init` command. Please look over the README.md file for more information on applicatiton initialization and scaffolding.

https://github.com/popphp/pop-kettle/blob/master/README.md

**Comment by ghost** [comment]
Ok, Thanks. But I've meant creating a single controller with for example a command like:

`./kettle create:controller <controllerName>`

and for a view like:

`./kettle create:view <viewName>`

and so on, after the initial scaffolding.
And I can't find something like it, in the README.md file or in the docs.

**Comment by nicksagona** [comment]
Ok I understand. However, what would go in those files? Are they just blank files? At this point, what's going into the app can/will be subjective to the dev making the decisions. (That's the main reason `pop-kettle`'s feature-set stops where it does.)

If the view is just a blank `phtml` file for the dev to start writing code into, then that could just be achieved with a simple `touch app/view/new-view.phtml` command.

As for a controller file, where does that go? Depending on what type of project you've wired up, you'd probably need to direct it the `Http` or `Console` namespace, etc. And do any action methods go into it?

There's a lot of things to consider for a request like this. I think it would need to be discussed and planned out further before it's considered. I'm open to any discussion on it.

**Comment by ghost** [comment]
I think it needs to be planned out further as well. At first I thought about just having it create a blank controller class without any methods inside it, but I'm not sure. It might work with the script asking a bunch of questions after the initial start of the command. I'll put it on hold in the back of my mind for some days, so I can think more clearly about it.

**Comment by ghost** [comment]
I have now made up my mind.

When creating a controller, you do that (as a developer) with the following command:

`./kettle create:controller [--web] [--api] [--cli] <className>`

I think it's enough if a web- or api-controller only have an index method inside (to start with).
Haven't thought about the console, but I guess it will work in a similar way.

When creating a view, the command will be:

`./kettle create:view [--web] <viewName>`

and contain something like this:

```
<!DOCTYPE html>
<html>
<head>
    <title><?=$title; ?></title>
</head>
<body>
    <h1><?=$title;?></h1>
</body>
</html>
```

**Comment by nicksagona** [comment]
Ok, please see the newly release v1.4.0 which now includes `create` commands to assist in creating starter MVC application files. Thanks.
