### ISSUE TITLE
Some kettle commands doesn't work when detached from the docker container

### ISSUE THREAD

**Issue by ghost** [popphp/pop-kettle#6]
I'm using apache and php from one docker container, and mysql from another docker container.
They have a link between each other, using the "--link" parameter in docker. The mysql container
is linked with the name "db" against the "apache-php" container. The whole docker command
(when creating the container looks like this):

`docker run --name phpproject-apache-php -d --link mysql-container:db -p 80:80 -v /home/user/Projects/PhpProject:/var/www apache-php`

and the mysql docker container is created with the following command:

`docker run --name mysql-container -v /home/user/Data/MySQL-data:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=Password -d mysql:5`

`./kettle db:test` works only when I'm attaching to the docker container with `docker exec -it <containerId> /bin/bash`,
and running the kettle command "inside" the container. Outside the container I'll get this error message:

`MySQL Connection Error: php_network_getaddresses: getaddrinfo failed: nodename nor servname provided, or not known`

But some commands, like for instance: `./kettle db:create-seed` works outside the container without any issues.

Connecting to the database from the application code, works perfectly as well.

I'm not sure if its my docker container setup that's not working, or if its kettle that can't connect
to the database, with some commands, outside of the docker container (detached mode).

I'm going to test things out with my container setup, and will let you know if that is the case.
But I thought it would be best to write an issue about it here, as well.

**Comment by nicksagona** [comment]
I think this look like a pretty clear configuration issue with your docker set up. The error your posted has to do with your environment not seeing or be able to find the DB host (and nothing to do with pop-kettle itself.) Closing the issue out.
